language: generic

env:
  - CONDA_PY=3.7 CONDA_NPY=1.16

before_install:
  - sudo apt-get update
  - sudo apt-get install gfortran
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda config --set always_yes true
  - conda config --set anaconda_upload no
  - conda install -q python=$CONDA_PY numpy=$CONDA_NPY conda-build
  - python --version
  - python -c 'import numpy; print(numpy.__version__)'

install:
  - conda build --python=$CONDA_PY --numpy=$CONDA_NPY .

