{% set data = load_setup_py_data()%}

package:
  name: capytaine
  version: {{data.get('version')}}

source:
  path: ../

requirements:
  # build:
    # - {{ compiler('fortran') }}
    # - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - numpy>=1.15
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas>=1.3
    - scipy
    - xarray

build:
  entry_points:
    - capytaine = capytaine.ui.cli:main

test:
  imports:
    - capytaine
  requires:
    - pytest
    - hypothesis
  source_files:
    - pytest/*.py
    - pytest/**/*
  commands:
    - sudo apt-get install -y gmsh
    - pip install gmsh pygmsh
    - pytest
    - capytaine --help

about:
  home: {{data.get('url')}}
  license: {{data.get('license')}}
  license_file: LICENSE
  summary: {{data.get('description')}}
