name: Build and deploy documentation

on:
  pull_request:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - 'docs/**'
  #
  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Install Capytaine and other dependencies
        run: pip install .[docs]

      - name: Build documentation
        run: |
          cd docs && make

      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: ./docs/_build/html/
          repository-name: capytaine/capytaine.github.io
          branch: main
          target-folder: master/
          clean: true
