name: Build and test using latest available dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '5 5 5/15 * *'  # On the 5th and 20th of each month at 5:05

env:
  FORCE_COLOR: 3
  # Colors for nox

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.13']

    steps:

    - name: Checkout repository and submodules
      uses: actions/checkout@v4

    - name: Set up UV
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Run nox session
      run: uvx nox --force-python ${{ matrix.python-version }} -s build_and_test_on_latest_env editable_build_and_test_on_latest_env
